services:
  mirza-pro:
    build: .
    container_name: mirza-pro
    restart: unless-stopped
    
    environment:
      BOT_TOKEN: "${BOT_TOKEN}"
      ADMIN_ID: "${ADMIN_ID}"
      BOT_USERNAME: "${BOT_USERNAME}"
      DOMAIN: "${DOMAIN:-}"
      DB_NAME: "${DB_NAME:-mirza_pro}"
      DB_USER: "${DB_USER:-mirza_user}"
      DB_PASS: "${DB_PASS:-}"
    
    ports:
      - "${PORT:-8080}:80"
